"""task 14 consent and provider response

Revision ID: 00355e43f43b
Revises: 9c55ce1acbab
Create Date: 2026-09-03 03:08:24.049504
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '00355e43f43b'
down_revision = '9c55ce1acbab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        # Existing customers are opted in, matching the seeded default. A shop
        # that wants the opposite flips them in the UI.
        batch_op.add_column(
            sa.Column(
                'marketing_opt_in',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('provider_response')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('marketing_opt_in')

    # ### end Alembic commands ###
