"""task 1 initial schema

Revision ID: 3b00584523b0
Revises: 
Create Date: 2026-09-02 22:10:26.871401
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3b00584523b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('llm_instruction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key', 'language', name='uq_template_key_language')
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_template_key'), ['template_key'], unique=False)

    op.create_table('verticals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('unit_labels', sa.JSON(), nullable=False),
    sa.Column('default_config', sa.JSON(), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('product_schema', sa.JSON(), nullable=False),
    sa.Column('prompt_profile', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verticals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verticals_code'), ['code'], unique=True)

    op.create_table('reminder_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('signal', sa.String(length=48), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vertical_id', 'kind', name='uq_reminder_rule_vertical_kind')
    )
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_rules_vertical_id'), ['vertical_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('google_review_url', sa.String(length=512), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_vertical_id'), ['vertical_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('occasion', sa.String(length=96), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_store_id'), ['store_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('anniversary', sa.Date(), nullable=True),
    sa.Column('family_head_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_head_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'phone', name='uq_customer_store_phone')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_store_id'), ['store_id'], unique=False)

    op.create_table('daily_sales_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('invoices', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unique_customers', sa.Integer(), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', name='uq_daily_summary_store_date')
    )
    with op.batch_alter_table('daily_sales_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sales_summary_store_id'), ['store_id'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('suggestions_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_store_id'), ['store_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_category_store_name')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_store_id'), ['store_id'], unique=False)

    op.create_table('store_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'key', name='uq_store_config_store_key')
    )
    with op.batch_alter_table('store_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_config_store_id'), ['store_id'], unique=False)

    op.create_table('churn_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('scored_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('churn_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_churn_scores_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_churn_scores_store_id'), ['store_id'], unique=False)

    op.create_table('customer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=48), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_records_customer_id'), ['customer_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('hsn_code', sa.String(length=12), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_product_store_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['reminder_rules.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_store_id'), ['store_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=16), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=True),
    sa.Column('frequency_90d', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'customer_id', name='uq_segment_store_customer')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_store_id'), ['store_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'invoice_no', name='uq_txn_store_invoice')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_txn_store_created', ['store_id', 'created_at'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=48), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_product_id'), ['product_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_store_id'), ['store_id'], unique=False)

    op.create_table('stock_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('last_received_at', sa.DateTime(), nullable=True),
    sa.Column('last_sold_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_items_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_items_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_items_product_id'))

    op.drop_table('transaction_items')
    op.drop_table('stock_levels')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_store_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_customer_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_product_id'))

    op.drop_table('batches')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_store_created')
        batch_op.drop_index(batch_op.f('ix_transactions_store_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_store_id'))
        batch_op.drop_index(batch_op.f('ix_segments_customer_id'))

    op.drop_table('segments')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_store_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_kind'))
        batch_op.drop_index(batch_op.f('ix_reminders_customer_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_store_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('customer_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_records_customer_id'))

    op.drop_table('customer_records')
    with op.batch_alter_table('churn_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_churn_scores_store_id'))
        batch_op.drop_index(batch_op.f('ix_churn_scores_customer_id'))

    op.drop_table('churn_scores')
    with op.batch_alter_table('store_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_config_store_id'))

    op.drop_table('store_config')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_store_id'))

    op.drop_table('product_categories')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insights_store_id'))

    op.drop_table('insights')
    with op.batch_alter_table('daily_sales_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sales_summary_store_id'))

    op.drop_table('daily_sales_summary')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_store_id'))

    op.drop_table('customers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_store_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_vertical_id'))

    op.drop_table('stores')
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_rules_vertical_id'))

    op.drop_table('reminder_rules')
    with op.batch_alter_table('verticals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verticals_code'))

    op.drop_table('verticals')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_template_key'))

    op.drop_table('message_templates')
    # ### end Alembic commands ###
