"""task 17 indexes on foreign keys and hot paths

Revision ID: 4e24ea21b264
Revises: 15034b8b87f0
Create Date: 2026-09-03 03:36:35.937429
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4e24ea21b264'
down_revision = '15034b8b87f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_scores', schema=None) as batch_op:
        batch_op.create_index('ix_churn_store_risk', ['store_id', 'risk_level'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_family_head', ['family_head_id'], unique=False)
        batch_op.create_index('ix_customers_store_name', ['store_id', 'name'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_store_status', ['store_id', 'status'], unique=False)
        batch_op.create_index('ix_jobs_transaction', ['transaction_id'], unique=False)

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index('ix_product_categories_parent', ['parent_id'], unique=False)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_rule', ['rule_id'], unique=False)
        batch_op.create_index('ix_reminders_store_sent', ['store_id', 'sent_at'], unique=False)
        batch_op.create_index('ix_reminders_store_status_kind', ['store_id', 'status', 'kind'], unique=False)

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_store_segment', ['store_id', 'segment'], unique=False)

    with op.batch_alter_table('stock_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_stock_forecasts_product', ['product_id'], unique=False)

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.create_index('ix_stock_levels_last_sold', ['last_sold_at'], unique=False)

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.create_index('ix_txn_items_product_txn', ['product_id', 'transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_items_product_txn')

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_levels_last_sold')

    with op.batch_alter_table('stock_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_forecasts_product')

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_store_segment')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_store_status_kind')
        batch_op.drop_index('ix_reminders_store_sent')
        batch_op.drop_index('ix_reminders_rule')

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_product_categories_parent')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_transaction')
        batch_op.drop_index('ix_jobs_store_status')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_store_name')
        batch_op.drop_index('ix_customers_family_head')

    with op.batch_alter_table('churn_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_churn_store_risk')

    # ### end Alembic commands ###
