"""task 11 stock forecasts

Revision ID: 612e809698d2
Revises: f5fc6d03f35d
Create Date: 2026-09-03 02:51:06.616444
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '612e809698d2'
down_revision = 'f5fc6d03f35d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('days_to_stockout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('predicted_daily_velocity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('suggested_reorder_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_dead_stock_risk', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_forecasts_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_stock_forecasts_store_product', ['store_id', 'product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_forecasts_store_product')
        batch_op.drop_index(batch_op.f('ix_stock_forecasts_store_id'))

    op.drop_table('stock_forecasts')
    # ### end Alembic commands ###
