"""task 15 coupons loyalty referrals attribution

Revision ID: 873292ee0445
Revises: 00355e43f43b
Create Date: 2026-09-03 03:15:28.967574
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '873292ee0445'
down_revision = '00355e43f43b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('customers_reached', sa.Integer(), nullable=False),
    sa.Column('visits_attributed', sa.Integer(), nullable=False),
    sa.Column('revenue_attributed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coupons_redeemed', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_stats_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=False),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'code', name='uq_coupon_store_code')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_store_id'), ['store_id'], unique=False)

    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'customer_id', name='uq_loyalty_store_customer')
    )
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_store_id'), ['store_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('referrer_customer_id', sa.Integer(), nullable=False),
    sa.Column('referred_customer_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['referrer_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'code', name='uq_referral_store_code')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referred_customer_id'), ['referred_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_customer_id'), ['referrer_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_store_id'), ['store_id'], unique=False)

    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('loyalty_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loyalty_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loyalty_account_id'], ['loyalty_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_ledger_account', ['loyalty_account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_ledger_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_ledger_transaction_id'))
        batch_op.drop_index('ix_loyalty_ledger_account')

    op.drop_table('loyalty_ledger')
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_coupon_id'))

    op.drop_table('coupon_redemptions')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_store_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_customer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referred_customer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_code'))

    op.drop_table('referrals')
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_store_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_customer_id'))

    op.drop_table('loyalty_accounts')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_store_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_code'))
        batch_op.drop_index(batch_op.f('ix_coupons_campaign_id'))

    op.drop_table('coupons')
    with op.batch_alter_table('campaign_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_stats_campaign_id'))

    op.drop_table('campaign_stats')
    # ### end Alembic commands ###
