"""task 12 batch allocation on transaction items

Revision ID: 9c55ce1acbab
Revises: 612e809698d2
Create Date: 2026-09-03 03:03:20.441298
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9c55ce1acbab'
down_revision = '612e809698d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_allocation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_column('batch_allocation')

    # ### end Alembic commands ###
