"""task 9 llm cache

Revision ID: a642cf8a0102
Revises: 3b00584523b0
Create Date: 2026-09-03 02:28:45.369172
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a642cf8a0102'
down_revision = '3b00584523b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index('ix_llm_cache_hash_created', ['prompt_hash', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_cache_prompt_hash'), ['prompt_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cache_prompt_hash'))
        batch_op.drop_index('ix_llm_cache_hash_created')

    op.drop_table('llm_cache')
    # ### end Alembic commands ###
