"""task 10 model runs

Revision ID: f5fc6d03f35d
Revises: a642cf8a0102
Create Date: 2026-09-03 02:42:23.579875
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f5fc6d03f35d'
down_revision = 'a642cf8a0102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('rows_trained', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_store_id'))

    op.drop_table('model_runs')
    # ### end Alembic commands ###
